# folder where the data is downloaded
data_root: /data/concept-graphs/scannetpp_openlex_v2

# Set True to render depth for iphone frames
render_iphone: True
# Set True to render depth for dslr frames
render_dslr: False

splits: [nvs_sem_train, nvs_sem_val]

# Specify scene ids if you want to render depth for specific scenes
scene_ids: [8a35ef3cfe, 0a7cc12c0e, 4c5c60fa76]

# The near and far planes for the depth camera during rendering in meters.
near: 0.05
far: 20.0

# Output directory for the rendered depth images. If not given, the output will be saved to data folder in data_root
output_dir: /data/concept-graphs/scannetpp_openlex_v2/data

# SAM2 checkpoints directory and config
sam2_checkpoint_dir: /home/kumaraditya/checkpoints/sam2.1_hiera_large.pt
sam2_model_cfg: configs/sam2.1/sam2.1_hiera_l.yaml
